In [1]:
import pandas as pd

In [2]:
races = pd.read_csv("Formula1_2024season_raceResults.csv")
races23 = pd.read_csv("Formula1_2023season_raceResults.csv")

In [3]:
races.head()

,Track,Position,No,Driver,Team,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time
0,Bahrain,1,1,Max Verstappen,Red Bull Racing Honda RBPT,1,57,1:31:44.742,26,Yes,1:32.608
1,Bahrain,2,11,Sergio Perez,Red Bull Racing Honda RBPT,5,57,+22.457,18,No,1:34.364
2,Bahrain,3,55,Carlos Sainz,Ferrari,4,57,+25.110,15,No,1:34.507
3,Bahrain,4,16,Charles Leclerc,Ferrari,2,57,+39.669,12,No,1:34.090
4,Bahrain,5,63,George Russell,Mercedes,3,57,+46.788,10,No,1:35.065

In [4]:
races.shape

(479, 11)

In [5]:
races23.shape

(440, 11)

In [6]:
races["Team"].value_counts()

Team
Red Bull Racing Honda RBPT      48
Ferrari                         48
Mercedes                        48
McLaren Mercedes                48
Aston Martin Aramco Mercedes    48
Kick Sauber Ferrari             48
Haas Ferrari                    48
RB Honda RBPT                   48
Alpine Renault                  48
Williams Mercedes               47
Name: count, dtype: int64

In [7]:
races23["Team"].value_counts()

Team
Red Bull Racing Honda RBPT      44
Aston Martin Aramco Mercedes    44
Ferrari                         44
Mercedes                        44
Alfa Romeo Ferrari              44
Alpine Renault                  44
Williams Mercedes               44
AlphaTauri Honda RBPT           44
Haas Ferrari                    44
McLaren Mercedes                44
Name: count, dtype: int64

In [8]:
races.dtypes

Track               object
Position            object
No                   int64
Driver              object
Team                object
Starting Grid        int64
Laps                 int64
Time/Retired        object
Points               int64
Set Fastest Lap     object
Fastest Lap Time    object
dtype: object

In [9]:
races["stl_code"]= races["Set Fastest Lap"].astype("category").cat.codes

In [10]:
races["team_code"]= races["Team"].astype("category").cat.codes

In [11]:
races["pos_code"]= races["Position"].astype("category").cat.codes

In [12]:
races["target"]= (races["Position"]=="1").astype("int")

In [13]:
races

,Track,Position,No,Driver,Team,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time,stl_code,team_code,pos_code,target
0,Bahrain,1,1,Max Verstappen,Red Bull Racing Honda RBPT,1,57,1:31:44.742,26,Yes,1:32.608,1,8,0,1
1,Bahrain,2,11,Sergio Perez,Red Bull Racing Honda RBPT,5,57,+22.457,18,No,1:34.364,0,8,11,0
2,Bahrain,3,55,Carlos Sainz,Ferrari,4,57,+25.110,15,No,1:34.507,0,2,13,0
3,Bahrain,4,16,Charles Leclerc,Ferrari,2,57,+39.669,12,No,1:34.090,0,2,14,0
4,Bahrain,5,63,George Russell,Mercedes,3,57,+46.788,10,No,1:35.065,0,6,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,Abu Dhabi,16,20,Kevin Magnussen,Haas Ferrari,14,57,+1 lap,0,Yes,1:25.637,1,3,7,0
475,Abu Dhabi,17,30,Liam Lawson,RB Honda RBPT,12,55,DNF,0,No,1:28.751,0,7,8,0
476,Abu Dhabi,NC,77,Valtteri Bottas,Kick Sauber Ferrari,9,30,DNF,0,No,1:29.482,0,4,21,0
477,Abu Dhabi,NC,43,Franco Colapinto,Williams Mercedes,20,26,DNF,0,No,1:29.411,0,9,21,0
478,Abu Dhabi,NC,11,Sergio Perez,Red Bull Racing Honda RBPT,10,0,DNF,0,No,NaN,0,8,21,0

In [14]:

races23["stl_code"]= races23["Set Fastest Lap"].astype("category").cat.codes
races23["team_code"]= races23["Team"].astype("category").cat.codes
races23["pos_code"]= races["Position"].astype("category").cat.codes
races23["target"]= (races23["Position"]=="1").astype("int")
races23

,Track,Position,No,Driver,Team,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time,stl_code,team_code,pos_code,target
0,Bahrain,1,1,Max Verstappen,Red Bull Racing Honda RBPT,1,57,1:33:56.736,25,No,1:36.236,0,8,0,1
1,Bahrain,2,11,Sergio Perez,Red Bull Racing Honda RBPT,2,57,+11.987,18,No,1:36.344,0,8,11,0
2,Bahrain,3,14,Fernando Alonso,Aston Martin Aramco Mercedes,5,57,+38.637,15,No,1:36.156,0,3,13,0
3,Bahrain,4,55,Carlos Sainz,Ferrari,4,57,+48.052,12,No,1:37.130,0,4,14,0
4,Bahrain,5,44,Lewis Hamilton,Mercedes,7,57,+50.977,10,No,1:36.546,0,7,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,Abu Dhabi,16,2,Logan Sargeant,Williams Mercedes,20,58,+87.791,0,No,1:28.580,0,9,8,0
436,Abu Dhabi,17,24,Guanyu Zhou,Alfa Romeo Ferrari,19,58,+89.422,0,No,1:28.746,0,0,9,0
437,Abu Dhabi,18,55,Carlos Sainz,Ferrari,16,57,DNF,0,No,1:29.452,0,4,21,0
438,Abu Dhabi,19,77,Valtteri Bottas,Alfa Romeo Ferrari,18,57,+1 lap,0,No,1:29.863,0,0,21,0
439,Abu Dhabi,20,20,Kevin Magnussen,Haas Ferrari,17,57,+1 lap,0,No,1:29.934,0,5,0,0

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:


feature_columns = ['Starting Grid', 'stl_code', 'team_code'] 
target_column = 'target'

# Prepare the train and test sets
train = races23[feature_columns + ['target']]  # Use races23 for training
test = races[feature_columns + ['target']]    # Use races for testing

# Split the features and the target for both datasets
X_train = train[feature_columns]  # Features for training
y_train = train[target_column] # Target for training

X_test = test[feature_columns]   # Features for testing
y_test = test[target_column]   # Target for testing

# Initialize and train the model
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)
rf.fit(X_train, y_train)

# Predict on the test set
y_pred = rf.predict(X_test)
combined = pd.DataFrame(dict(actual=y_test, predicted=y_pred), index=y_test.index)
  

# Evaluate the model 
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

Model Accuracy: 0.94

In [17]:
from sklearn.metrics import precision_score

In [18]:
precision_score(y_test, y_pred)

0.4

In [19]:
grouped_races= races.groupby(["Team","Driver"])

In [20]:
grouped_races23= races23.groupby(["Team","Driver"])

In [21]:
group = grouped_races.get_group(("Ferrari", "Carlos Sainz")).sort_index()

In [22]:
group2 = grouped_races23.get_group(("Ferrari", "Carlos Sainz")).sort_index()

In [23]:
group

,Track,Position,No,Driver,Team,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time,stl_code,team_code,pos_code,target
2,Bahrain,3,55,Carlos Sainz,Ferrari,4,57,+25.110,15,No,1:34.507,0,2,13,0
40,Australia,1,55,Carlos Sainz,Ferrari,2,58,1:20:26.843,25,No,1:20.031,0,2,0,1
61,Japan,3,55,Carlos Sainz,Ferrari,4,53,+20.866,15,No,1:33.841,0,2,13,0
83,China,5,55,Carlos Sainz,Ferrari,7,56,+33.983,10,No,1:39.764,0,2,15,0
103,Miami,5,55,Carlos Sainz,Ferrari,3,57,+16.407,10,No,1:30.928,0,2,15,0
123,Emilia Romagna,5,55,Carlos Sainz,Ferrari,4,63,+22.325,10,No,1:20.220,0,2,15,0
141,Monaco,3,55,Carlos Sainz,Ferrari,3,78,+7.585,15,No,1:14.726,0,2,13,0
174,Canada,NC,55,Carlos Sainz,Ferrari,12,52,DNF,0,No,1:18.957,0,2,21,0
184,Spain,6,55,Carlos Sainz,Ferrari,6,66,+31.028,8,No,1:18.539,0,2,16,0
201,Austria,3,55,Carlos Sainz,Ferrari,4,71,+4.533,15,No,1:09.282,0,2,13,0
223,Great Britain,5,55,Carlos Sainz,Ferrari,7,52,+47.318,11,Yes,1:28.293,1,2,15,0
244,Hungary,6,55,Carlos Sainz,Ferrari,4,70,+23.073,8,No,1:21.441,0,2,16,0
265,Belgium,6,55,Carlos Sainz,Ferrari,7,44,+19.795,8,No,1:46.364,0,2,16,0
283,Netherlands,5,55,Carlos Sainz,Ferrari,10,72,+32.137,10,No,1:14.117,0,2,15,0
302,Italy,4,55,Carlos Sainz,Ferrari,5,53,+15.621,12,No,1:23.219,0,2,14,0
336,Azerbaijan,18,55,Carlos Sainz,Ferrari,3,49,DNF,0,No,1:46.866,0,2,9,0
345,Singapore,7,55,Carlos Sainz,Ferrari,10,62,+96.039,6,No,1:36.561,0,2,17,0
360,United States,2,55,Carlos Sainz,Ferrari,3,56,+8.562,18,No,1:37.763,0,2,11,0
379,Mexico,1,55,Carlos Sainz,Ferrari,1,71,1:40:55.800,25,No,1:20.137,0,2,0,1
414,Brazil,NC,55,Carlos Sainz,Ferrari,20,38,DNF,0,No,1:24.201,0,2,21,0
421,Las Vegas,3,55,Carlos Sainz,Ferrari,2,50,+11.906,15,No,1:35.875,0,2,13,0
444,Qatar,6,55,Carlos Sainz,Ferrari,7,57,+17.476,8,No,1:23.465,0,2,16,0
460,Abu Dhabi,2,55,Carlos Sainz,Ferrari,3,58,+5.832,18,No,1:27.765,0,2,11,0

In [24]:
def rolling_averages(group,cols,new_cols):
    group=group.sort_index()
    rolling_stats=group[cols].rolling(3).mean()
    if rolling_stats.shape[1] == len(new_cols):
        group[new_cols] = rolling_stats
    else:
        raise ValueError(f"The number of columns in rolling_stats ({rolling_stats.shape[1]}) does not match the length of new_cols ({len(new_cols)})")
    #group[new_cols]=rolling_stats
    group=group.dropna(subset=new_cols)
    return group

In [25]:
cols=["pos_code","Starting Grid","Points"]
new_cols = [f"{c}_rolling" for c in cols]

In [26]:
rolling_averages(group,cols,new_cols)

,Track,Position,No,Driver,Team,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time,stl_code,team_code,pos_code,target,pos_code_rolling,Starting Grid_rolling,Points_rolling
61,Japan,3,55,Carlos Sainz,Ferrari,4,53,+20.866,15,No,1:33.841,0,2,13,0,8.666667,3.333333,18.333333
83,China,5,55,Carlos Sainz,Ferrari,7,56,+33.983,10,No,1:39.764,0,2,15,0,9.333333,4.333333,16.666667
103,Miami,5,55,Carlos Sainz,Ferrari,3,57,+16.407,10,No,1:30.928,0,2,15,0,14.333333,4.666667,11.666667
123,Emilia Romagna,5,55,Carlos Sainz,Ferrari,4,63,+22.325,10,No,1:20.220,0,2,15,0,15.000000,4.666667,10.000000
141,Monaco,3,55,Carlos Sainz,Ferrari,3,78,+7.585,15,No,1:14.726,0,2,13,0,14.333333,3.333333,11.666667
174,Canada,NC,55,Carlos Sainz,Ferrari,12,52,DNF,0,No,1:18.957,0,2,21,0,16.333333,6.333333,8.333333
184,Spain,6,55,Carlos Sainz,Ferrari,6,66,+31.028,8,No,1:18.539,0,2,16,0,16.666667,7.000000,7.666667
201,Austria,3,55,Carlos Sainz,Ferrari,4,71,+4.533,15,No,1:09.282,0,2,13,0,16.666667,7.333333,7.666667
223,Great Britain,5,55,Carlos Sainz,Ferrari,7,52,+47.318,11,Yes,1:28.293,1,2,15,0,14.666667,5.666667,11.333333
244,Hungary,6,55,Carlos Sainz,Ferrari,4,70,+23.073,8,No,1:21.441,0,2,16,0,14.666667,5.000000,11.333333
265,Belgium,6,55,Carlos Sainz,Ferrari,7,44,+19.795,8,No,1:46.364,0,2,16,0,15.666667,6.000000,9.000000
283,Netherlands,5,55,Carlos Sainz,Ferrari,10,72,+32.137,10,No,1:14.117,0,2,15,0,15.666667,7.000000,8.666667
302,Italy,4,55,Carlos Sainz,Ferrari,5,53,+15.621,12,No,1:23.219,0,2,14,0,15.000000,7.333333,10.000000
336,Azerbaijan,18,55,Carlos Sainz,Ferrari,3,49,DNF,0,No,1:46.866,0,2,9,0,12.666667,6.000000,7.333333
345,Singapore,7,55,Carlos Sainz,Ferrari,10,62,+96.039,6,No,1:36.561,0,2,17,0,13.333333,6.000000,6.000000
360,United States,2,55,Carlos Sainz,Ferrari,3,56,+8.562,18,No,1:37.763,0,2,11,0,12.333333,5.333333,8.000000
379,Mexico,1,55,Carlos Sainz,Ferrari,1,71,1:40:55.800,25,No,1:20.137,0,2,0,1,9.333333,4.666667,16.333333
414,Brazil,NC,55,Carlos Sainz,Ferrari,20,38,DNF,0,No,1:24.201,0,2,21,0,10.666667,8.000000,14.333333
421,Las Vegas,3,55,Carlos Sainz,Ferrari,2,50,+11.906,15,No,1:35.875,0,2,13,0,11.333333,7.666667,13.333333
444,Qatar,6,55,Carlos Sainz,Ferrari,7,57,+17.476,8,No,1:23.465,0,2,16,0,16.666667,9.666667,7.666667
460,Abu Dhabi,2,55,Carlos Sainz,Ferrari,3,58,+5.832,18,No,1:27.765,0,2,11,0,13.333333,4.000000,13.666667

In [27]:
rolling_averages(group2, cols, new_cols)

,Track,Position,No,Driver,Team,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time,stl_code,team_code,pos_code,target,pos_code_rolling,Starting Grid_rolling,Points_rolling
51,Australia,12,55,Carlos Sainz,Ferrari,5,58,+6.594,0,No,1:20.467,0,4,3,0,11.000000,4.333333,6.666667
64,Azerbaijan,5,55,Carlos Sainz,Ferrari,4,51,+45.491,10,No,1:45.175,0,4,16,0,11.666667,4.333333,6.000000
84,Miami,5,55,Carlos Sainz,Ferrari,3,57,+42.511,10,No,1:31.362,0,4,16,0,11.666667,4.000000,6.666667
107,Monaco,8,55,Carlos Sainz,Ferrari,4,78,+63.391,4,No,1:16.449,0,4,19,0,17.000000,3.666667,8.000000
124,Spain,5,55,Carlos Sainz,Ferrari,2,66,+45.698,10,No,1:18.403,0,4,16,0,17.000000,3.000000,8.000000
144,Canada,5,55,Carlos Sainz,Ferrari,11,70,+21.540,10,No,1:15.911,0,4,16,0,17.000000,5.666667,8.000000
165,Austria,6,55,Carlos Sainz,Ferrari,3,71,+31.377,8,No,1:08.880,0,4,17,0,16.333333,5.333333,9.333333
189,Great Britain,10,55,Carlos Sainz,Ferrari,5,52,+19.448,1,No,1:31.366,0,4,2,0,11.666667,6.333333,6.333333
207,Hungary,8,55,Carlos Sainz,Ferrari,11,70,+71.073,4,No,1:22.584,0,4,19,0,12.666667,6.333333,4.333333
238,Belgium,NC,55,Carlos Sainz,Ferrari,4,23,DNF,0,No,1:53.138,0,4,21,0,14.000000,6.666667,1.666667
244,Netherlands,5,55,Carlos Sainz,Ferrari,6,72,+12.541,10,No,1:14.934,0,4,16,0,18.666667,7.000000,4.666667
262,Italy,3,55,Carlos Sainz,Ferrari,1,51,+11.193,15,No,1:25.501,0,4,13,0,16.666667,3.666667,8.333333
280,Singapore,1,55,Carlos Sainz,Ferrari,1,62,1:46:37.418,25,No,1:37.666,0,4,11,1,13.333333,2.666667,16.666667
305,Japan,6,55,Carlos Sainz,Ferrari,6,53,+50.221,8,No,1:36.187,0,4,17,0,13.666667,2.666667,16.000000
339,Qatar,NC,55,Carlos Sainz,Ferrari,12,0,DNS,0,No,NaN,0,4,0,0,9.333333,6.333333,11.000000
343,United States,3,55,Carlos Sainz,Ferrari,4,56,+15.134,15,No,1:40.034,0,4,15,0,10.666667,7.333333,7.666667
363,Mexico,4,55,Carlos Sainz,Ferrari,2,71,+27.154,12,No,1:22.539,0,4,15,0,10.000000,6.000000,9.000000
385,Brazil,6,55,Carlos Sainz,Ferrari,7,71,+50.188,8,No,1:14.406,0,4,17,0,15.666667,4.333333,11.666667
405,Las Vegas,6,55,Carlos Sainz,Ferrari,12,50,+20.834,8,No,1:35.984,0,4,17,0,16.333333,7.000000,9.333333
437,Abu Dhabi,18,55,Carlos Sainz,Ferrari,16,57,DNF,0,No,1:29.452,0,4,21,0,18.333333,11.666667,5.333333

In [28]:
races_rolling = races.groupby(["Team", "Driver"]).apply(lambda x: rolling_averages(x, cols, new_cols), include_groups=False)

In [29]:
races_rolling23= races23.groupby(["Team", "Driver"]).apply(lambda x: rolling_averages(x, cols, new_cols), include_groups=False)

In [30]:
races_rolling

                                               Track Position  No  \
Team              Driver
Alpine Renault    Esteban Ocon   55        Australia       16  31
                                 73            Japan       15  31
                                 89            China       11  31
                                 108           Miami       10  31
                                 132  Emilia Romagna       14  31
...                                              ...      ...  ..
Williams Mercedes Logan Sargeant 217         Austria       19   2
                                 229   Great Britain       11   2
                                 255         Hungary       17   2
                                 276         Belgium       17   2
                                 294     Netherlands       16   2

                                      Starting Grid  Laps Time/Retired  \
Team              Driver
Alpine Renault    Esteban Ocon   55              15    57       +1 lap
                                 73              15    52       +1 lap
                                 89              13    56      +62.812
                                 108             13    57      +39.746
                                 132             12    62       +1 lap
...                                             ...   ...          ...
Williams Mercedes Logan Sargeant 217             19    69      +2 laps
                                 229             12    52      +88.960
                                 255             14    69       +1 lap
                                 276             18    44      +86.057
                                 294             18    71       +1 lap

                                      Points Set Fastest Lap Fastest Lap Time  \
Team              Driver
Alpine Renault    Esteban Ocon   55        0              No         1:21.354
                                 73        0              No         1:36.232
                                 89        0              No         1:40.937
                                 108       1              No         1:32.037
                                 132       0              No         1:21.304
...                                      ...             ...              ...
Williams Mercedes Logan Sargeant 217       0              No         1:10.406
                                 229       0              No         1:29.972
                                 255       0              No         1:20.561
                                 276       0              No         1:47.490
                                 294       0              No         1:15.539

                                      stl_code  team_code  pos_code  target  \
Team              Driver
Alpine Renault    Esteban Ocon   55          0          0         7       0
                                 73          0          0         6       0
                                 89          0          0         2       0
                                 108         0          0         1       0
                                 132         0          0         5       0
...                                        ...        ...       ...     ...
Williams Mercedes Logan Sargeant 217         0          9        10       0
                                 229         0          9         2       0
                                 255         0          9         8       0
                                 276         0          9         8       0
                                 294         0          9         7       0

                                      pos_code_rolling  Starting Grid_rolling  \
Team              Driver
Alpine Renault    Esteban Ocon   55           6.333333              17.000000
                                 73           5.666667              15.666667
                                 89           5.000000              14.333333
                                 108          3.000000              13.666667
                                 132          2.666667              12.666667
...                                                ...                    ...
Williams Mercedes Logan Sargeant 217         14.333333              17.000000
                                 229          8.000000              16.666667
                                 255          6.666667              15.000000
                                 276          6.000000              14.666667
                                 294          7.666667              16.666667

                                      Points_rolling
Team              Driver
Alpine Renault    Esteban Ocon   55         0.000000
                                 73         0.000000
                                 89         0.000000
                                 108        0.333333
                                 132        0.333333
...                                              ...
Williams Mercedes Logan Sargeant 217        0.000000
                                 229        0.000000
                                 255        0.000000
                                 276        0.000000
                                 294        0.000000

[431 rows x 16 columns]

In [31]:
races_rolling23

                                               Track Position  No  \
Team               Driver
Alfa Romeo Ferrari Guanyu Zhou    48       Australia        9  24
                                  78      Azerbaijan       NC  24
                                  95           Miami       16  24
                                  112         Monaco       13  24
                                  128          Spain        9  24
...                                              ...      ...  ..
Williams Mercedes  Logan Sargeant 351  United States       10   2
                                  375         Mexico       16   2
                                  390         Brazil       11   2
                                  415      Las Vegas       16   2
                                  435      Abu Dhabi       16   2

                                       Starting Grid  Laps Time/Retired  \
Team               Driver
Alfa Romeo Ferrari Guanyu Zhou    48              17    58       +5.713
                                  78              15    36          DNF
                                  95              14    57      +78.440
                                  112             19    77       +1 lap
                                  128             13    66      +71.878
...                                              ...   ...          ...
Williams Mercedes  Logan Sargeant 351             16    56      +87.998
                                  375             19    70          DNF
                                  390             19    70       +1 lap
                                  415              6    50      +50.882
                                  435             20    58      +87.791

                                       Points Set Fastest Lap  \
Team               Driver
Alfa Romeo Ferrari Guanyu Zhou    48        2              No
                                  78        0              No
                                  95        0              No
                                  112       0              No
                                  128       2              No
...                                       ...             ...
Williams Mercedes  Logan Sargeant 351       1              No
                                  375       0              No
                                  390       0              No
                                  415       0              No
                                  435       0              No

                                      Fastest Lap Time  stl_code  team_code  \
Team               Driver
Alfa Romeo Ferrari Guanyu Zhou    48          1:21.819         0          0
                                  78          1:47.553         0          0
                                  95          1:31.736         0          0
                                  112         1:16.926         0          0
                                  128         1:18.753         0          0
...                                                ...       ...        ...
Williams Mercedes  Logan Sargeant 351         1:41.238         0          9
                                  375         1:23.003         0          9
                                  390         1:15.738         0          9
                                  415         1:37.740         0          9
                                  435         1:28.580         0          9

                                       pos_code  target  pos_code_rolling  \
Team               Driver
Alfa Romeo Ferrari Guanyu Zhou    48         19       0         10.000000
                                  78         21       0         14.666667
                                  95          8       0         16.000000
                                  112         5       0         11.333333
                                  128         1       0          4.666667
...                                         ...     ...               ...
Williams Mercedes  Logan Sargeant 351         4       0          7.666667
                                  375         8       0          7.333333
                                  390         3       0          5.000000
                                  415        21       0         10.666667
                                  435         8       0         10.666667

                                       Starting Grid_rolling  Points_rolling
Team               Driver
Alfa Romeo Ferrari Guanyu Zhou    48               13.666667        0.666667
                                  78               14.333333        0.666667
                                  95               15.333333        0.666667
                                  112              16.000000        0.000000
                                  128              15.333333        0.666667
...                                                      ...             ...
Williams Mercedes  Logan Sargeant 351              17.000000        0.333333
                                  375              16.666667        0.333333
                                  390              18.000000        0.333333
                                  415              14.666667        0.000000
                                  435              15.000000        0.000000

[396 rows x 16 columns]

In [32]:
races_rolling.to_csv("f124_team_driver_data.csv", index=False)

In [33]:
races_rolling=races_rolling.droplevel(['Team','Driver'])

In [34]:
races_rolling23=races_rolling23.droplevel(['Team','Driver'])

In [35]:
races_rolling

,Track,Position,No,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time,stl_code,team_code,pos_code,target,pos_code_rolling,Starting Grid_rolling,Points_rolling
55,Australia,16,31,15,57,+1 lap,0,No,1:21.354,0,0,7,0,6.333333,17.000000,0.000000
73,Japan,15,31,15,52,+1 lap,0,No,1:36.232,0,0,6,0,5.666667,15.666667,0.000000
89,China,11,31,13,56,+62.812,0,No,1:40.937,0,0,2,0,5.000000,14.333333,0.000000
108,Miami,10,31,13,57,+39.746,1,No,1:32.037,0,0,1,0,3.000000,13.666667,0.333333
132,Emilia Romagna,14,31,12,62,+1 lap,0,No,1:21.304,0,0,5,0,2.666667,12.666667,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Austria,19,2,19,69,+2 laps,0,No,1:10.406,0,9,10,0,14.333333,17.000000,0.000000
229,Great Britain,11,2,12,52,+88.960,0,No,1:29.972,0,9,2,0,8.000000,16.666667,0.000000
255,Hungary,17,2,14,69,+1 lap,0,No,1:20.561,0,9,8,0,6.666667,15.000000,0.000000
276,Belgium,17,2,18,44,+86.057,0,No,1:47.490,0,9,8,0,6.000000,14.666667,0.000000
294,Netherlands,16,2,18,71,+1 lap,0,No,1:15.539,0,9,7,0,7.666667,16.666667,0.000000

In [36]:
races_rolling23

,Track,Position,No,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time,stl_code,team_code,pos_code,target,pos_code_rolling,Starting Grid_rolling,Points_rolling
48,Australia,9,24,17,58,+5.713,2,No,1:21.819,0,0,19,0,10.000000,13.666667,0.666667
78,Azerbaijan,NC,24,15,36,DNF,0,No,1:47.553,0,0,21,0,14.666667,14.333333,0.666667
95,Miami,16,24,14,57,+78.440,0,No,1:31.736,0,0,8,0,16.000000,15.333333,0.666667
112,Monaco,13,24,19,77,+1 lap,0,No,1:16.926,0,0,5,0,11.333333,16.000000,0.000000
128,Spain,9,24,13,66,+71.878,2,No,1:18.753,0,0,1,0,4.666667,15.333333,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,United States,10,2,16,56,+87.998,1,No,1:41.238,0,9,4,0,7.666667,17.000000,0.333333
375,Mexico,16,2,19,70,DNF,0,No,1:23.003,0,9,8,0,7.333333,16.666667,0.333333
390,Brazil,11,2,19,70,+1 lap,0,No,1:15.738,0,9,3,0,5.000000,18.000000,0.333333
415,Las Vegas,16,2,6,50,+50.882,0,No,1:37.740,0,9,21,0,10.666667,14.666667,0.000000
435,Abu Dhabi,16,2,20,58,+87.791,0,No,1:28.580,0,9,8,0,10.666667,15.000000,0.000000

In [37]:
races_rolling.index=range(races_rolling.shape[0])

In [38]:
races_rolling

,Track,Position,No,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time,stl_code,team_code,pos_code,target,pos_code_rolling,Starting Grid_rolling,Points_rolling
0,Australia,16,31,15,57,+1 lap,0,No,1:21.354,0,0,7,0,6.333333,17.000000,0.000000
1,Japan,15,31,15,52,+1 lap,0,No,1:36.232,0,0,6,0,5.666667,15.666667,0.000000
2,China,11,31,13,56,+62.812,0,No,1:40.937,0,0,2,0,5.000000,14.333333,0.000000
3,Miami,10,31,13,57,+39.746,1,No,1:32.037,0,0,1,0,3.000000,13.666667,0.333333
4,Emilia Romagna,14,31,12,62,+1 lap,0,No,1:21.304,0,0,5,0,2.666667,12.666667,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,Austria,19,2,19,69,+2 laps,0,No,1:10.406,0,9,10,0,14.333333,17.000000,0.000000
427,Great Britain,11,2,12,52,+88.960,0,No,1:29.972,0,9,2,0,8.000000,16.666667,0.000000
428,Hungary,17,2,14,69,+1 lap,0,No,1:20.561,0,9,8,0,6.666667,15.000000,0.000000
429,Belgium,17,2,18,44,+86.057,0,No,1:47.490,0,9,8,0,6.000000,14.666667,0.000000
430,Netherlands,16,2,18,71,+1 lap,0,No,1:15.539,0,9,7,0,7.666667,16.666667,0.000000

In [39]:
races_rolling23.index=range(races_rolling23.shape[0])

In [40]:
def make_predictions(data1,data2,feature_columns):

    # Prepare the train and test sets
    train = data2[feature_columns + ['target']]  # Use races23 for training
    test = data1[feature_columns + ['target']]    # Use races for testing
    
    # Split the features and the target for both datasets
    X_train = train[feature_columns] # Features for training
    y_train = train[target_column] # Target for training
    
    X_test = test[feature_columns] # Features for testing
    y_test = test[target_column] # Target for testing
    
    # Initialize and train the model
    rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)
    rf.fit(X_train, y_train)
    
    # Predict on the test set
    y_pred = rf.predict(X_test)
    combined = pd.DataFrame(dict(actual=y_test, predicted=y_pred), index=y_test.index)
      
    
    # Evaluate the model 
    from sklearn.metrics import accuracy_score
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Model Accuracy: {accuracy:.2f}")

    from sklearn.metrics import precision_score
    precision = precision_score(test["target"], y_pred)
    print(f"Model precision: {precision:.2f}")
    return combined, precision

In [41]:
combined, error = make_predictions(races_rolling, races_rolling23,feature_columns + new_cols)

Model Accuracy: 0.96
Model precision: 0.71

In [42]:
combined

     actual  predicted
0         0          0
1         0          0
2         0          0
3         0          0
4         0          0
..      ...        ...
426       0          0
427       0          0
428       0          0
429       0          0
430       0          0

[431 rows x 2 columns]

In [43]:
combined = combined.merge(races_rolling[["Track", "No"]], left_index=True, right_index=True, suffixes=('_combined', '_races_rolling'))

combined

     actual  predicted           Track  No
0         0          0       Australia  31
1         0          0           Japan  31
2         0          0           China  31
3         0          0           Miami  31
4         0          0  Emilia Romagna  31
..      ...        ...             ...  ..
426       0          0         Austria   2
427       0          0   Great Britain   2
428       0          0         Hungary   2
429       0          0         Belgium   2
430       0          0     Netherlands   2

[431 rows x 4 columns]